export ZDOTDIR=$HOME/.config/zsh
export MOZ_ENABLE_WAYLAND=1
export MOZ_WEBRENDER=0
export QT_QPA_PLATFORM=wayland-egl
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QUICK_CONTROLS_STYLE=org.kde.desktop
export DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1
export BEMENU_BACKEND=wayland
